//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A6: return "28 - Digital Input 7";
		case Gpio::A8: return "3 - OUT 6";
		case Gpio::A9: return "7 - OUT 2";
		case Gpio::B1: return "27 - Digital Input 6";
		case Gpio::C13: return "Internal not for use - Ignition 1";
		case Gpio::C6: return "17 - OUT 10";
		case Gpio::D10: return "5 - OUT 4";
		case Gpio::D11: return "6 - OUT 3";
		case Gpio::D12: return "1 - OUT 8";
		case Gpio::D13: return "9 - OUT 9";
		case Gpio::D15: return "2 - OUT 7";
		case Gpio::D2: return "4 - OUT 5";
		case Gpio::D3: return "8 - OUT 1";
		case Gpio::E1: return "Internal not for use - UART8 TX";
		case Gpio::E11: return "20 - VSS / HALL Input";
		case Gpio::E12: return "30 - Digital Input 1";
		case Gpio::E13: return "31 - Digital Input 2";
		case Gpio::E14: return "32 - Digital Input 3";
		case Gpio::E15: return "33 - Digital Input 4";
		case Gpio::E4: return "Internal not for use - Ignition 3";
		case Gpio::E5: return "Internal not for use - Ignition 2";
		default: return nullptr;
	}
	return nullptr;
}
